version: 2.1
jobs:
  compile:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: sudo apt install -qq bc zip clang zlib1g-dev libstdc++6
      - checkout
      - run: wget https://raw.githubusercontent.com/FauzanDhiyaul/script/master/CircleCI
      - run: chmod +x CircleCI
      - run: bash CircleCI
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
